services:
  caddy:
    container_name: caddy
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./Caddyfile.plausible:/etc/caddy/Caddyfile.plausible
      - ./Caddyfile.mateocafe:/etc/caddy/Caddyfile.mateocafe
      - ../website/web/static:/mateocafe
    networks:
      - fuzzylogic
    ports:
      - 80:80
      - 443:443
    env_file:
      - .env

networks:
  fuzzylogic:
    external: true
