services:
  caddy:
    container_name: caddy
    build: .
    restart: always
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./Caddyfile.plausible:/etc/caddy/Caddyfile.plausible
    networks:
      - fuzzylogic
    ports:
      - 80:80
      - 443:443
    env_file:
      - .env

networks:
  fuzzylogic:
    external: true
